"""empty message

Revision ID: 5aa7eeb29663
Revises: 
Create Date: 2019-08-28 11:05:44.387412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa7eeb29663'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KidneyData',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('specific_gravity', sa.Float(), nullable=True),
    sa.Column('Albumin', sa.Integer(), nullable=True),
    sa.Column('Blood_Gluc_rand', sa.Integer(), nullable=True),
    sa.Column('Blood_Urea', sa.Integer(), nullable=True),
    sa.Column('Serum_Cr', sa.Float(), nullable=True),
    sa.Column('sodium', sa.Integer(), nullable=True),
    sa.Column('Hemoglobin', sa.Float(), nullable=True),
    sa.Column('packed_cell_volume', sa.Integer(), nullable=True),
    sa.Column('rbc_cnt', sa.Float(), nullable=True),
    sa.Column('htn', sa.Integer(), nullable=True),
    sa.Column('diabetes', sa.Integer(), nullable=True),
    sa.Column('actual_class', sa.Integer(), nullable=True),
    sa.Column('predicted_class', sa.Integer(), nullable=True),
    sa.Column('CreateDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('KidneyData')
    # ### end Alembic commands ###
